version = 1

[warpspace]
name = "jedit-echo-dev"

[repos.wesley]
git = "https://github.com/flyingrobots/wesley.git"
rev = "d5e264427f0888c5010c7fe228a44bc24f00ba98"
path = "wesley"

[repos.echo]
git = "https://github.com/flyingrobots/echo.git"
rev = "c2328292cd6742c34d45a7ddd2b0ac3b94a92c30"
path = "echo"

[repos.jedit]
git = "https://github.com/flyingrobots/jedit.git"
rev = "a7d9fbf2ec5c1168da453e51c9912041ad795aae"
path = "jedit"

[repos.warp-ttd]
git = "https://github.com/flyingrobots/warp-ttd.git"
rev = "eb80aa4b762e74513ddb79dd575113491109efb9"
path = "warp-ttd"

[crates]
wesley-core = "0.0.2"

[contracts.jedit-text]
repo = "jedit"
schema = "contracts/jedit-text.graphql"
generator_repo = "echo"
generator = "echo-wesley-gen"
